using pd.concat() instead of pd.merge()
VForWaTer/metacatalog pull request #171
Opened 2021-09-15 10:28 UTC by AlexDo1

Always merge Split datasets additionally.

The default parameters of [pd.concat()](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) should fit our use case.

2021-09-15 10:53 UTC, mmaelicke requested changes
Hey, thanks. But I think this needs some more logic to be only applied to `Split datasets` and not to `Composites`.

2021-09-15 10:53 UTC, mmaelicke commented on metacatalog/util/results.py
> +        if self.group is not None and self.group.type.name in ('Composite', 'Split dataset'):
I think we need to handle Composites and Split datasets separately, as composites should be merged and split datasets should be concatenated

2021-09-15 10:53 UTC, mmaelicke commented on metacatalog/util/results.py
> +                    all_data = pd.concat([all_data, dat])
I think this only works for Split datasets as Composites were handled correctly. For a composite, the data resulting from different entries should be *merged* along a common index axis

2021-09-15 11:45 UTC, AlexDo1 commented
The latest commit uses the 'old' `pd.merge()` function for `Composites` and `pd.concat` for `Split datasets` now.

**Composite: Eddy data**:
![image](https://user-images.githubusercontent.com/23619690/133427300-464dfd64-9271-475a-9063-dfaa7f5376f7.png)

**Split dataset: LUBW gauge data**:
![image](https://user-images.githubusercontent.com/23619690/133427388-cc46fea7-e494-465d-8904-59b788725fa0.png)

2021-09-15 11:49 UTC, mmaelicke reviewed
That looks way better now, thanks a lot!
Is there an easy way to add a unit-test for the changed behavior? If yes, that would be cool, if not, never mind and merge.

2021-09-15 14:28 UTC, AlexDo1 commented
> That looks way better now, thanks a lot!
> Is there an easy way to add a unit-test for the changed behavior? If yes, that would be cool, if not, never mind and merge.

I think you tested most of the merging behavior of `Split datasets` here:
https://github.com/VForWaTer/metacatalog/blob/3c547d4ab06178a41c347bc23afd1cf5dfa17f22/metacatalog/test/test_array_type_data.py#L246-L280

I just copied most of that test for a second test with a `Composite dataset` and tested for the shape of the merged data.
I guess we could test for more stuff here, I just focused on the merging behavior.

2022-07-01 14:37 UTC, AlexDo1 commented
From our conversation above, I understand that the tests are not perfect, but we should still be able to merge the PR since the results look good.

2022-07-01 14:39 UTC, mmaelicke commented
It's not so easy to continue a discussion after 10 months :) But I agree, it should be fine to merge.

2022-07-01 14:42 UTC, merged