entries.location nullable + db revision
VForWaTer/metacatalog pull request #186
Opened 2022-10-05 13:15 UTC by AlexDo1

Column `location` in table `entries` is now nullable, as spatial / raster data cannot be represented as POINT location.
`Datasource.spatial_scale.extent` should be used instead for PLOYGON locations.

2022-10-08 04:35 UTC, mmaelicke commented
I am still not sure if we should enforce `POINT` geometries for overview maps. Alternatively, drop the location altogether and introduce a view of POINTS, derived from spatial extent table....

2022-12-09 10:47 UTC, AlexDo1 commented
The RADKLIM metadata entry is now added to the database `metacatalog-dev` on the server and can serve as an example for how we want to handle locations now.
I did not use `NULL` for `entries.location` but the centroid of the RADOLAN grid.
**With this PR, we could / should use `NULL`, the centroid of the grid is then calculated from the spatial extent for the [location View](https://github.com/VForWaTer/metacatalog/blob/location_nullable/metacatalog/db/views/locations.sql):**
https://github.com/VForWaTer/metacatalog/blob/9655d0691db8f5c8b57bcd3b6b423b69217b1b7a/metacatalog/db/views/locations.sql#L9-L21

Here is a screenshot of the location View, which also shows the area of the column `geom`:

![Bildschirmfoto vom 2022-12-09 11-35-17](https://user-images.githubusercontent.com/23619690/206684453-b07d3d57-ff79-40c5-b222-8dd8a9b14007.png)

This map shows all `point locations`, with the RADKLIM location as the centroid of the grid:

![Bildschirmfoto vom 2022-12-09 10-51-56](https://user-images.githubusercontent.com/23619690/206678165-cbae9dcf-920c-4239-9c17-5b58b8fcf588.png)

And this shows the column `geom` with the actual shape of the extent / the RADOLAN grid:

![Bildschirmfoto vom 2022-12-09 10-49-33](https://user-images.githubusercontent.com/23619690/206674221-b0d30190-efa6-4018-bfb5-aeefd5eedff4.png)

@mmaelicke @MarcusStrobl we should discuss how we want to handle and store locations, especially `POLYGON` locations.

2022-12-09 10:59 UTC, mmaelicke commented
Thanks @AlexDo1!

I guess, with this in place, we can make the location column nullable and remove the point for RADKLIM data. The view should then generate the centroid as a point for the `point_location` view column, right?

I guess the key here is the `area` column, as we can request the geometries depending on the Map zoom level. For a small zoom level (ie 2, almost world-view) the Geoserver level should use only `geom` that have a **minimum** size, effectively shrinking the rectangle around BaWü to its centroid, but at the same time the Radklim can still be viewed. If we are closer (ie. zoom level 12), BaWür would use the POLYGON as well.

So to come back to your question: we add `location` as point, whenever that makes sense, we add the `geom`, if there is a Non-Point representation of the spatial domain of measurements (ie. catchment) and we set the geometry inside the spatial scale of the datasource as a bounding box (effectively the extent of all measurements) as required by INSPIRE/ISO 19115. 
The distinction between the datasource.spatial_scale.extent and the entry.geom is not 100% clear, I guess, and we can discuss this. My 2 cents on this: the `geom` is the area, that is represented by the measurements (so its about the data), while the spatial extent is the covered area (so its about the metadata).

2022-12-09 11:30 UTC, mmaelicke requested changes
There are some merge conflicts, please have a look at my review comments, these should sort the conflicts out.

2022-12-09 11:30 UTC, mmaelicke commented on metacatalog/__version__.py
> +__version__ = '0.5.3'
We are already at version `0.6.0`

2022-12-09 11:30 UTC, mmaelicke commented on metacatalog/db/revisions/__init__.py
> +    rev10,
This can't be correct, there is already a revision 10, containing the current state of netCDF readers.

2022-12-09 11:30 UTC, mmaelicke commented on metacatalog/db/revisions/rev10.py
> +"""
See my other comment, I think this has to be renamed to `rev11`

2022-12-09 11:30 UTC, mmaelicke commented on metacatalog/models/datasource.py
> +        .. versionchanged:: 0.5.3
wrong version

2022-12-12 08:52 UTC, mmaelicke approved these changes

2022-12-12 09:00 UTC, merged