ImmutableResultSet unittests
VForWaTer/metacatalog pull request #232
Opened 2023-01-24 16:20 UTC by AlexDo1

This PR adds further unittests for `ImmutableResultSets`.  
Closes #229

2023-01-24 17:00 UTC, mmaelicke requested changes

2023-01-25 08:32 UTC, AlexDo1 commented on metacatalog/test/test_result_set.py
> +                     'version', 'location', 'embargo', 'isPartial']
I shortened the list of expected keys as you suggested.

2023-01-25 08:33 UTC, AlexDo1 commented on metacatalog/test/test_result_set.py
> +@pytest.mark.depends(on=['add_find'], name='resultset')
Yes, until now, no other test depends on the resultset test.

2023-01-25 08:33 UTC, AlexDo1 commented on metacatalog/test/test_result_set.py
> +    assert result_set_check_resultset_of_resultset(session)
Yes, thanks!

2023-01-25 08:34 UTC, AlexDo1 commented on metacatalog/test/test_result_set.py
> +    assert rs._members > 0
Yes, I adapted that.

2023-01-25 16:02 UTC, mmaelicke approved these changes

2023-01-26 09:26 UTC, merged